# Springboot2.1.2默认引入的mysql版本version是8.0.13，其driver-class-name为com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# type-aliases-package批量设置别名作用：就是在mapper.xml文件中直接写类名，不配置就需要写类的全路径名
mybatis:
  type-aliases-package: cn.com.kun.common.vo
  mapper-locations: classpath:mapping/*.xml

# 将mapper接口所在包的日志级别改成debug，可以在控制台打印sql
logging:
  config: classpath:log4j2-spring.properties
  level:
    com.example.demo.mapper: debug